# Generated by Django 3.1 on 2020-08-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f', '0002_students_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_Name', models.CharField(max_length=20)),
                ('TelePhone', models.PositiveIntegerField()),
                ('CompanyUrl', models.URLField()),
                ('Type_Of_Business', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='students',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='school_id',
            new_name='subject_id',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='subject_name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='document',
        ),
        migrations.RemoveField(
            model_name='students',
            name='school',
        ),
        migrations.AddField(
            model_name='students',
            name='Age',
            field=models.PositiveIntegerField(default=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='Email',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='TelePhone',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='is_currently_student',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
