# Generated by Django 3.1 on 2020-08-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f', '0003_auto_20200825_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='CompanyUrl',
            new_name='Company_Url',
        ),
    ]
